### ISSUE TITLE
Create plan for next nodebotsday

### ISSUE THREAD

**Issue by hackygolucky** [PDXNode/nodebotsday#8]
See ceejbot and rockbot CascadiaJS2013 talks for great intros and ideas. 

Do we want a whole day? Series of evening workshops? BYOH?

Plan for EARLY 2014

**Comment by wraithan** [comment]
I will be BYOH.

Series of workshops is cool, if you make to each of them, otherwise folks will be discouraged from coming to later ones if they miss a night. But, it allows for building up to cool projects.

Single day: logistics is easier, especially getting all the kits there, as well as any snacks and sponsorship needed. Downside is it is a lot of time for people to get lost and end up not actually accomplish anything. Someone leading a workshop for an initial portion then letting folks go free would make it more effective than last time.

I am +1 on both (not helpful).
